---
title: "R bootcamp syllabus"
author: "Ana Bento and Reni Kaul"
date: "`r Sys.Date()`"
output: pdf_document
---

#Friday 

#8am-9am: M1 -- What is R lecture 


#9am-9:05am: Break

#9:10-12:00pm: M2+M3 -- Data Types and Manipulation 

##M2
###Vectors
###Matrices
###Factors
###Dataframes
###Lists


##M3 -- Data Manipulation

###Exercises- Reni


#12:00-1:15pm:  Lunch

#1:15-3:00p:  M4 -- Writing your first script

##Lecture on functions-- brief ppt
###hmtl document with  functions, summary stats and fixing errors- loops apply functions function that has a summary stats

#3:00-3:05: Break
\newpage
#3:15pm- 4:30pm: The script

###creating your first script
###commenting 
###exchanging


#Saturday

#8am-9am: Recap script  + scramble exercise
open your script on their own anf then exercise

#9:15am: Break

#9:25am:12:15pm: M6 Data visualiztion M6  

###basic, gg plottly

###exercise collaborative coding 

#12:15-1:15pm: Lunch (pizza provided)

#1:15-3:00pm: M7-- Simulations

##Simulationg data in R

###Exercise incorporating all skills

#3:00pm: Break

#3:15-5:00pm

###Continuation

###Wrap up







